Repository iamakashrout/Online-Medical-Consultation, pull requests merged in 2025-03, with the labels that each got.

#20 edit profile functionality added
  backend/.gitignore
  backend/app.js
  backend/package-lock.json
  backend/package.json
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/edit/[email].js
  frontend/src/pages/patientUpdate/[email].js
Labels: pwoc, easy

#22 Pre-fill input while editing
  frontend/src/pages/edit/[email].js
  frontend/src/pages/patientUpdate/[email].js
Labels: pwoc, easy

#23 Integrate Medical Chatbot #13
  README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/HelpButton.jsx
  frontend/src/components/HelpChat.jsx
  frontend/src/pages/Patient_Login.jsx
  frontend/src/pages/api/gemini.js
  frontend/src/utils/context.js
Labels: pwoc, hard

#24 Solved #17: Rating and Review Systems for Doctors
  backend/app.js
  backend/models/doctorModel.js
  backend/models/reviewModel.js
  backend/routes/reviewRoutes.js
  frontend/src/components/ListOfDoctors.jsx
  frontend/src/helper.js
  frontend/src/pages/view_profile.jsx
Labels: pwoc, medium

#27 edit prescription made, delete prescription + add prescription updated
  backend/app.js
  backend/models/patientModel.js
  frontend/src/pages/editPrescription/[email]/[prescriptionId].js
  frontend/src/pages/patientPrescription/[email].js
  frontend/src/pages/patientProfile/[email].js
Labels: pwoc, medium

#32 voice search feature added
  frontend/src/components/HelpChat.jsx
  frontend/src/utils/voicespeech.jsx
Labels: pwoc, medium

#35 dockerized the webapp
  backend/.dockerignore
  backend/Dockerfile
  docker-compose.yaml
  frontend/.dockerignore
  frontend/Dockerfile
Labels: pwoc, medium

#48 Solve #42: Added Text to Speech converter on Responses generated by ChatBot
  frontend/package-lock.json
  frontend/src/components/HelpChat.jsx
Labels: pwoc, hard

#50 Solved #46 : Added a Notification Bell on Doctor's side indicating number of "pending" requests
  backend/controllers/doctor.js
  backend/routes/requestRoutes.js
  frontend/src/pages/Bell.jsx
  frontend/src/pages/findDoctor/[email].js
Labels: pwoc, medium

#53 doctor reviews on doctor profile + prefilled values in edit doctor
  frontend/src/pages/editDoctor/[email].js
  frontend/src/pages/findDoctor/[email].js
Labels: pwoc, medium

#57 Solved #54 : Highlighted current word being spoken by the voice in chatbot
  frontend/src/components/HelpChat.jsx
Labels: pwoc, medium

#59 Solved #58 : Optimised Search Bar functionality and Sorting of Docs by Rating (Highest first and Lowest first)
  frontend/src/components/ListOfDoctors.jsx
Labels: pwoc, medium

#62 Solved #60 : Enabled Voice Search on the Search Bar
  frontend/src/components/ListOfDoctors.jsx
  frontend/src/components/VoiceSearch.jsx
Labels: pwoc, medium

#64 Implemented Search History caching using Redis #16
  backend/app.js
  backend/controllers/searchControllers.js
  backend/package-lock.json
  backend/package.json
  backend/routes/searchRoutes.js
  backend/utils/redis.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ListOfDoctors.jsx
Labels: pwoc, hard

#67 Solved #66 : Fixed all UI issues + Dark Mode 2.0
  frontend/src/pages/DoctorRequests.js
  frontend/src/pages/PatientRequests.js
  frontend/src/pages/editDoctor/[email].js
  frontend/src/pages/findDoctor/[email].js
  frontend/src/pages/patientPrescription/[email].js
  frontend/src/pages/patientProfile/[email].js
  frontend/src/styles/globals.css
Labels: pwoc, medium
